
//PHONE Config
const PHONE_USERNAME = 'paterlini.luca@gmail.com';
const PHONE_HASH = '1ddcade41396b223592ec2e469a012ba5079c31bac7f9952a7837ab4fc7718d3';
const PHONE_SMS_SENDER = 'The Racing Manager';
const PHONE_TEST_FLAG = 1;// set 0 for real money

// AWS Config
const EMAIL_PORT = 587;
const EMAIL_FROM = "info@theracingmanager.com";
const EMAIL_SUBJECT = "Good Morning";
const EMAIL_CONFIRMATION_CODE_LEN = 20;
const TARGET_DOMAIN = "127.0.0.1";
const TARGET_PORT = 5000;

// Generics
const BUF_LEN_SCRYPT = 64;
const SALT_N = 10;
const SESSION_SECONDS=3600*24;
const SESSION_MAX = 9;
const PHONE_CONFIRM_CODE_LEN = 6;

// System

const MEDIA_SAVE_PATH = "/home/pater92/Desktop/TRM_APP_API/Research/TRM_API/DATA";
const DATABASE_NAME = "trm";

module.exports = {
    'PHONE_USERNAME':'PHONE_USERNAME',
    'PHONE_HASH': 'PHONE_HASH',
    'PHONE_SMS_SENDER':'PHONE_SMS_SENDER',
    'PHONE_TEST_FLAG':'PHONE_TEST_FLAG',
    'EMAIL_PORT':'EMAIL_PORT',
    'EMAIL_FROM':'EMAIL_FROM',
    'EMAIL_SUBJECT':'EMAIL_SUBJECT',
    'EMAIL_CONFIRMATION_CODE_LEN':'EMAIL_CONFIRMATION_CODE_LEN',
    'TARGET_DOMAIN':'TARGET_DOMAIN',
    'TARGET_PORT':'TARGET_PORT',
    'BUF_LEN_SCRYPT':'BUF_LEN_SCRYPT',
    'SALT_N':'SALT_N',
    'BLOB':'BLOB',
    'SESSION_SECONDS':'SESSION_SECONDS',
    'SESSION_MAX':'SESSION_MAX',
    'PHONE_CONFIRM_CODE_LEN':'PHONE_CONFIRM_CODE_LEN',
    'MEDIA_SAVE_PATH':'MEDIA_SAVE_PATH',
    'DATABASE_NAME':'DATABASE_NAME'
};