const PRIMARY_COLOR = [
  'BLANCHED ALMOND',
  'LEMON YELLOW',
  'BUBBLE GUM',
  'CARROT ORANGE',
  'MEDIUM TUSCAN RED',
  'RED PIGMENT',
  'CRIMSON GLORY',
  'LIGHT PASTEL PURPLE',
  'KSU PURPLE',
  'BABY BLUE EYES',
  'HONOLULU BLUE',
  'USAFA BLUE',
  'GREEN RYB',
  'GREEN CRAYOLA',
  'BOTTLE GREEN',
  'PLATINUM',
  'MANATEE',
  'DARK GUNMETAL'
]

module.exports = {
  PRIMARY_COLOR
}
